### ISSUE TITLE
Transition to GitHub Actions for Larger CI Testing

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#1050]
Recently, _Rcpp_ has been bitten by issues arising on macOS and old _R_ versions.

The current promise is _Rcpp_ should support R >= 3.0.0, per `DESCRIPTION`:

https://github.com/RcppCore/Rcpp/blob/dda407a723a1d4a7664011a650b22fce69319326/DESCRIPTION#L17

The testing setup uses [a single Docker container](https://hub.docker.com/r/rcpp/ci/dockerfile) based off of the official [Docker image for r-base built by the Rocker project](https://hub.docker.com/_/r-base) to test the results:

https://github.com/RcppCore/Rcpp/blob/dda407a723a1d4a7664011a650b22fce69319326/docker/ci/Dockerfile#L3

https://github.com/RcppCore/Rcpp/blob/dda407a723a1d4a7664011a650b22fce69319326/.travis.yml#L12-L13

I'm proposing a shift over to using parallelized tests across Windows, macOS, and Linux via GitHub Actions via @jimhester's phenomenal [GitHub Actions for _R_ workflow](https://github.com/r-lib/actions). I'm more than happy to lead the transition. I've been using various forms of it since its inception in 2019. 

Thoughts: @jjallaire @kevinushey @eddelbuettel @thirdwing

**Comment by eddelbuettel** [comment]
Not in favour yet.  I started to look at GH actions but I am far from sold.

**Comment by thirdwing** [comment]
I agree that it is great to have tests running on Windows and macOS.

Do we really need a complete transition to GH Actions?

Can we add Windows/macOS tests first?

**Comment by eddelbuettel** [comment]
macOS is such a [redacted]; I have no domain knowledge or expertise or time to babysit it.  

windows is similar but marginally more reliable because it is more constrained due to Rtools.  We also test some via win-builder. It is also in transition.

If someone wants to start a community driven parallel testing repo where they want to go crazy on a dozen different different config, I would encourage that.  I will try my best to look at it time permitting.
Both get tested pre-release via rhub.  

Really, the one thing that would help is a rev.dep setup for different arches.  If someone wants to contribute that, maybe even the R Consortium would support modest hardware (or cloud cpu) outlays.  But I spend sufficient time on Linux with rev.dep to catch at least some issues that I (sadly) cannot volunteer for this.

**Comment by eddelbuettel** [comment]
Also worth noting that an expanded test matrix would not have caught the _architecture-dependent_ reverse dependency issue with `execinfo.h`.

**Comment by eddelbuettel** [comment]
There does not seem to be an awful lot of excitement for the proposal so I am going to close this.  

But I took the opporttunity to add a matrix, so we now test from oldoldrel to dev just like CRAN. On Linux.  The other OSs remain a little more work to handle, and generally get covered only via rhub.

Given that our CI use is Docker-based, switching to another CI provider is easy enough if/when we decide it is needed. I don't see a need now, but we're always open for suggestions and can revisit.
