### ISSUE TITLE
Making push_back amortized constant

### ISSUE THREAD

**Issue by thk686** [RcppCore/Rcpp#1096]
R now has the capability to grow a vector beyond its length. This allows for push_back to increase the size and leave some allocated storage unused. By multiplying the storage length with each push_back that exceeds the current storage length, you get amortized constant cost. I really miss this from std::vector, so I made a fork and implemented the changes. If this is considered a good idea, I can prepare a pull request.

**Comment by eddelbuettel** [comment]
Hi Tim.  

Thanks for the proposal.  There are (at least) two key aspects to this.  

One is that as I recall `SEXP` always (?) (or at least for a loooong time, or do I have this wrong? Was this an ALTREP change?) was able to overcommit like a stl vector. We just didn't use it.  So yes, one could. (More below).

Two is a plain "why bother"? We documented that `push_back` (as implemented) is expensive due to the resulting full copies.  So we told people to use STL vectors.  Please explain what is wrong with that approach.  (Apart from maybe copying once at the end.  Do we _really_ care?)

We got burned *badly* on the last release cycle by two (as it turns out) unsufficiently careful PRs which had side effects (notably beyond the core reach of CRAN test machines).  With that I will now place the burden on you: 
 - demonstrate the PR has merit _a priori_ (which is what we are trying now)
 - actually deliver a clean PR
 - also demonstrate on a sufficiently large number of client package and architectures that there are no side effects
 - be patient as it is less than a week to a potent 1.0.5 upload so we are talking 1.0.6 release (which may in any event be the right timeline to be thinking about changes affect, more or less, just about every Rcpp application)

So, in sum, "yes, maybe".  But with a lowercase 'm'.  Convince me to make it uppercase.

**Comment by thk686** [comment]
On Sun, Jun 28, 2020 at 4:09 PM Dirk Eddelbuettel <notifications@github.com>
wrote:

> Hi Tim.
>
> Thanks for the proposal. There are (at least) two key aspects to this.
>
> One is that as I recall SEXP always (?) (or at least for a loooong time,
> or do I have this wrong? Was this an ALTREP change?) was able to overcommit
> like a stl vector. We just didn't use it. So yes, one could. (More below).
>
I don't know when it was added. I only noticed that capability recently.
There is a pp define in core R that when enabled causes a slight over
allocation to occur when appending to a vector. (Defaults to something like
5%, which is unfortunately too small to be useful.) So it is used in core R.

> Two is a plain "why bother"? We documented that push_back (as
> implemented) is expensive due to the resulting full copies. So we told
> people to use STL vectors. Please explain what is wrong with that approach.
> (Apart from maybe copying once at the end. Do we *really* care?)
>
Hmmm... I recall you chided me a long time ago about using std::vector
owing to the copies. Maybe that stuck. If people are happy with
std::vector, then I suppose the idea is moot. (I do generally prefer
std::vector just because I have a pretty good idea of its memory layout,
etc.)

> We got burned *badly* on the last release cycle by two (as it turns out)
> unsufficiently careful PRs which had side effects (notably beyond the core
> reach of CRAN test machines). With that I will now place the burden on you:
>
>    - demonstrate the PR has merit *a priori* (which is what we are trying
>    now)
>    - actually deliver a clean PR
>    - also demonstrate on a sufficiently large number of client package
>    and architectures that there are no side effects
>    - be patient as it is less than a week to a potent 1.0.5 upload so we
>    are talking 1.0.6 release (which may in any event be the right timeline to
>    be thinking about changes affect, more or less, just about every Rcpp
>    application)
>
> So, in sum, "yes, maybe". But with a lowercase 'm'. Convince me to make it
> uppercase.
>
Yes, I can see that core changes like this would need careful testing.

**Comment by eddelbuettel** [comment]
> Yes, I can see that core changes like this would need careful testing.

It would be worth it _if done right_ and gets us on the road towards possible other updates.  But we have to do it right, and it may not be fast.  If you have some time over the summer...

**Comment by eddelbuettel** [comment]
Closing as there was no follow-up. Feel free to reopen if a more substantial proposal emerges.

**Comment by thk686** [comment]
I unfortunately don't have sufficient time to do all the required testing,
and now we have cpp11, so I likely will not pursue further.
