### ISSUE TITLE
avoid using EXTPTR_PTR

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#1097]
As it's not part of the official R API. See https://r.789695.n4.nabble.com/Possible-ABI-change-in-R-4-0-1-td4764335.html for details.

We should use `R_ExternalPtrAddtr()` instead.

```
kevinushey@cdrv:~/r/pkg/Rcpp [master]
$ rg "EXTPTR_PTR"
inst/include/Rcpp/module/class.h
170:                vec_signed_method* mets = reinterpret_cast< vec_signed_method* >( EXTPTR_PTR( method_xp ) ) ;
197:                vec_signed_method* mets = reinterpret_cast< vec_signed_method* >( EXTPTR_PTR( method_xp ) ) ;
219:                vec_signed_method* mets = reinterpret_cast< vec_signed_method* >( EXTPTR_PTR( method_xp ) ) ;
396:                prop_class* prop = reinterpret_cast< prop_class* >( EXTPTR_PTR( field_xp ) ) ;
403:                prop_class* prop = reinterpret_cast< prop_class* >( EXTPTR_PTR( field_xp ) ) ;

src/api.cpp
148:    snprintf(buffer, 20, "%p", (void*)EXTPTR_PTR(xp));

src/module.cpp
56:    return EXTPTR_PTR(xp) == 0;
```

Evidently this change was done way back in 2011 as well for some usages:

https://github.com/RcppCore/Rcpp/blob/b1254701a899cb187f9a6917cb8d18c7f93290c7/ChangeLog#L6630-L6634

**Comment by eddelbuettel** [comment]
Sure, good catch.  Saw that discussion, and of course the ping-pong between @gaborcsardi and myself about the `roxygen2` issue he was pinning on us which I didn't want to have here ... til @jeroen found this underlying change.

Which, almost surely, is not related to the `roxygen2` issue as the above (which I also see here using `ag` rather than `rg`) affects only Modules which "some" package use, but not many -- and almost surely not `roxygen2`. 

Let me chew over if I want to tackle this this week or rather ship what we have now as 1.0.5 and then let a change such as this "rest and mature" a little en route to 1.0.6.  If that release happens.  Because I am still not over the nonsense I had to put up with in the discussion after 1.0.4 came out, and we had risked late changes.   Very little appetite for repeating that....

**Comment by eddelbuettel** [comment]
I misglanced the reference from `src/api.cpp`.  That is a pretty-printer, rather than the package status, so that could indeed be called more widely.

**Comment by eddelbuettel** [comment]
By the same token this and the code below in the same file may need a rethink:

https://github.com/RcppCore/Rcpp/blob/97222bb753c4cd76a4cef7d33c2bfc2e305d1158/src/barrier.cpp#L24

**Comment by eddelbuettel** [comment]
Hm, and
