### ISSUE TITLE
`r_cast` does not convert STRSXP to INTSXP

### ISSUE THREAD

**Issue by dipterix** [RcppCore/Rcpp#1111]
https://github.com/RcppCore/Rcpp/blob/47daf66f8f80a17171611cf4cae378068e75f614/inst/include/Rcpp/r_cast.h#L59-L67

Example case:

```cpp
SEXP example_rcpp(SEXP x){
  return as<IntegerVector>(x);
}
SEXP example_native(SEXP x){
  return Rf_coerceVector(x, INTSXP);
}

/*** R
x <- as.character(1:10)

# errored
example_rcpp()

example_native(x)
#> [1]  1  2  3  4  5  6  7  8  9 10

*/
```

**Comment by eddelbuettel** [comment]
I am sorry but it is early in the morning here and I do not see what you filed this about.

Could be so kind and maybe edit your post above and add why you think this an issue, i.e. maybe document why do you think we promise the caster converts from Character?  I do agree that it would be a nice to have, I also recall having gone to Boost and BH for that simply because it is not a simple issue.  But maybe I simply misunderstand what this issue is about for you -- so could you expand a little?

**Comment by kevinushey** [comment]
FWIW, `as<>` is normally used to convert from R / Rcpp types to C / C++ types; using `as<IntegerVector>()` here is less commonly seen.

This may also be an ALTREP issue since the thing returned by `as.character(1:10)` is "lazy" -- it's a deferred string conversion to a compact sequence.

Here's a more minimal example (that can be easily `sourceCpp()`-ed):

`````
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
SEXP example_rcpp(SEXP x) {
  return as<IntegerVector>(x);
}

/*** R
example_rcpp(as.character(1:10))
*/
`````

with result

```
> example_rcpp(letters)
Error in example_rcpp(letters) : 
  Not compatible with requested type: [type=character; target=integer].
```

**Comment by eddelbuettel** [comment]
But I think that is also a not-so-subtle misunderstanding of what `as<>()` does. I don't think it ever promised conversion from char.

**Comment by dipterix** [comment]
Example above uses `r_cast`.  I didn't know I was abusing `as<>`, but I just want to demonstrate `r_cast` cannot cast from STRSXP to INTSXP nor REALSXP. The issue has nothing to do with `as<>`.

Perhaps a more direct example

```cpp
#include <Rcpp.h>
using namespace Rcpp;


// [[Rcpp::export]]
SEXP example_rcpp(SEXP x){
  return r_cast<REALSXP>(x);
}



/*** R
example_rcpp('1')
*/
```

**Comment by eddelbuettel** [comment]
Why would you not use the high-level functions `as<>()` (from `SEXP`) and `wrap()` (to `SEXP`)  ?

**Comment by dipterix** [comment]
My function receive `SEXP` (int, double, cplx, or str) generated from c++ code from other packages. I need to convert whatever input I get to `IntegerVector`, or `std::vector<int>`. Is there any recommended way to do so with Rcpp?

**Comment by eddelbuettel** [comment]
I would say, and we also have a decade+ of documentation here, at GitHub, in ten vignettes, at the [Rcpp Gallery](https://gallery.rcpp.org/) -- and in dedicated example packages such as [RcppExamples](https://github.com/eddelbuettel/rcppexamples).  

But I can't tell what you tried. I'd be happy to help you but you have to give us something more to work with.

**Comment by eddelbuettel** [comment]
@dipterix Can you provide a minimal yet complete example of what you want to do, but cannot?

**Comment by dipterix** [comment]
@eddelbuettel Sorry for the late reply, I was trying to turn arbitrary array-like `SEXP` (such as numeric, character, or complex) into integers in Rcpp. `example_rcpp` was very close to what I'm doing. 

It seems that I misunderstood what `as<>` does and I'm not suppose to use `as<IntegerVector>(SEXP)` in Rcpp. Now I'm very confused how can I write `example_native` in Rcpp but instead of using `Rf_allocVector` and return SEXP, I can use full Rcpp functions and return an `Integervector`.

Thanks and really apologize for the delays.

**Comment by eddelbuettel** [comment]
>  Now I'm very confused how can I write example_native in Rcpp but instead of using Rf_allocVector and return SEXP

You should use `wrap()` just like the hundreds of Rcpp examples do:

```r
R> Rcpp::cppFunction("SEXP foo() { std::vector<int> a = { 1, 3, 5}; return wrap(a); }")
R> foo()
[1] 1 3 5
R> 
```

Does the above help?

**Comment by dipterix** [comment]
What I wanted to do was

```cpp
Integervector output(SEXP input){
  Integervector res = ...(input)
  return res;
}
```

`input` could be a character vector like `c('1', '1.2')`, I want the output to be like `c(1,1)` (identical to `as.character(c('1', '1.2'))`), but as `Integervector`

**Comment by eddelbuettel** [comment]
Thank you for _almost_ writing a full example as we had asked you repeatedly.  

Conversion from character is _not_ something Rcpp does natively, nor does Rcpp promise to do it. 

It is however a useful trick to know and use,  I myself need it in `anytime` and use Boost (via `BH`) for it relying on its `lexical_cast` header.  This is described in some detail [in this Rcpp Gallery story](https://gallery.rcpp.org/articles/a-second-boost-example/) as I mentioned (maybe too briefly) in my first answer.

I am closing this now as this is mostly a misunderstanding rather than an issue.  I may still be misunderstanding, so if there is something wrong please feel free to re-open but maybe also read [the issue ticket notes](https://github.com/RcppCore/Rcpp/blob/master/.github/ISSUE_TEMPLATE.md) more closely.
