### ISSUE TITLE
Question: rcpp::vector<int64>

### ISSUE THREAD

**Issue by kdkavanagh** [RcppCore/Rcpp#1117]
I'm curious what the recommended approach to creating an instantiation of `Rcpp::Vector<REALSXP>` but with int64 getters/operators might look like.  Currently, I've got tons of duplicated code across various rcpp functions to handle conversions to/from `double` <-> `int64_t` when the input has the `integer64` class attr, and setting the `integer64` class on the resulting `NumericVector`.  

Ideally I'd like to extend an instantiation of `NumericVector` to something like Int64Vector, though I can't see a great way to do this with the current usage of traits in the Vector class - Seems the only way would be to create a fake `RTYPE` and associate that with an R type of `REALSXP` and storage type of `int64_t`, then implement getters/setters to handle the `double` -> `int64` conversion.

Is this something you've attempted in the past, or am I better off wrapping an `rcpp::vector` in a custom class and implementing the vector API myself as a proxy over the `rcpp::vector`?

**Comment by eddelbuettel** [comment]
That is a great question.

And to the best of my knowledge (as well as some posted examples, see _e.g._ some posts at [the Rcpp Gallery](https://gallery.rcpp.org)) you cannot do that "generally".  We manage to _faithfully_ convert the payload of an `int64_t` into R's `integer64` (from the [bit64](http://cloud.r-project.org/package=bit64) package) by using `memcpy` (as casts will loose precision).  For example our [nanotime](http://cloud.r-project.org/package=nanotime) package does that for higher-precision timestamps (just like Python, Julia, ... do).  But this still requires you to _explicitly_ pass values from R as `integer64()` or else you accidentally flip to `double` and loose precision as you do in casts.  (In short: doubles have sixteen digits of precision; nanoseconds since epoch is 19 digits, so you again loose everything beyond the microsecond; ditto with other non-time payloads in the `int64_t` range---a `double` gets 'coarse' at high values).

Now all that said I am _for_ a better vector as a convenience over on the Rcpp side.  Many packages, including some of mine, repeat local ad-hoc solutions (and some packages even have nice solutions -- @knapply put some nice things into [RcppSimdJson](http://cloud.r-project.org/package=RcppSimdJson) but they requires a more modern compiler than the baseline we use for Rcpp.  So open for discussion.

And in short the problem you are hitting for lacking `RTYPE` is the very R constraint of not having a `SEXP` for this.  @ltierney has hinted (in a talk at the virtual useR! this summer) that changes may be coming to R but they will a) not be immediately and b) not bring us `int64_t`.  As given that all our type switching in Rcpp uses the `RTYPE` this risks being quite a bit of (potentially fragile?) work.

**Comment by knapply** [comment]
Is there anything preventing a `Rcpp::wrap()` specialization for `std::vector<int64_t>` to using the routine from [here](https://gallery.rcpp.org/articles/creating-integer64-and-nanotime-vectors/)?  It could then be gated behind some opt-in `RCPP_WRAP_STD_VEC_INT64T_AS_INTEGER64`-like macro.

**Comment by eddelbuettel** [comment]
I keep thinking about this, and I am leaning towards (possibly header-only) external package.
