### ISSUE TITLE
optimize sugar function

### ISSUE THREAD

**Issue by waynelapierre** [RcppCore/Rcpp#1127]
I am trying to find an Rcpp sugar function similar to R's optimize but there seems to be none. Have you considered adding one?

**Comment by eddelbuettel** [comment]
Looks like `optimize()` is itself a wrapper for an older Fortran implementation with a reference to the classic Brent text.  I recall having implemented Brent's `uniroot()` once with Rcpp (when I needed to "batch" a number of implied volatility calculations each of which involves a line search -- I may have used a routine borrowed from QuantLib then).

We never really ventured much into general "math" algorithms in Rcpp itself but there are a number of add-on packages (_e.g._ [RcppNumerical](https://cran.r-project.org/package=RcppNumerical) comes to mind).   So unless you want to propose an implementation you plan to provide the question may be better suited for the mailing list...

**Comment by waynelapierre** [comment]
I am also trying to calculate implied volatility using the Bisection/Brent method. That's why I asked this question. I will take a look at RcppNumerical, BH, and Nloptr.

**Comment by eddelbuettel** [comment]
Have a look at my blog.  I posted something years ago related to this---we were doing some 'bulk' calculations with implied volatilities and I brought some code "in" from RQuantLib / QuantLib just so save a round-trips.  Because the math of Brent is pretty easy the coding is too.

I agree that it would be a nice to have, but it also does not have to be inside of Rcpp.  We could simply cook something up as a small package with a solution in a header file -- I can possibly help you (time permitting) if you can take the lead.

**Comment by eddelbuettel** [comment]
The post I had in mind is this:  http://dirk.eddelbuettel.com/blog/2012/10/25/

**Comment by waynelapierre** [comment]
Thanks so much for the info. I found a Bisection function in Boost and I will copy the Brent method from RQuantLib.

**Comment by eddelbuettel** [comment]
Sounds good.  I will close this then.  Feel free to reopen if there is anything actionable for Rcpp.
