### ISSUE TITLE
compilation time 

### ISSUE THREAD

**Issue by waynelapierre** [RcppCore/Rcpp#1154]
Rcpp::sourceCpp's compilation time seems unrelated to whether I include the Rcpp header.
I only use functions and data types from C++ itself. Is there any way to make Rcpp::sourceCpp faster in my case?

**Comment by eddelbuettel** [comment]
Please provide a reproducible example just to focus the discussion.

Also, what OS?  Some are faster than others.

What tooling?  Do you know about `ccache` which I have been using for many years and written about....

**Comment by waynelapierre** [comment]
I could not provide the code due to legal issues. I am using GCC 10 on Red Hat Enterprise Linux. Could you please point me to the ccache reference? Thanks.

**Comment by eddelbuettel** [comment]
With all due respect, I am not trying to be difficult here, and you simply misunderstood.  I didn't ask for a copy of your umpteen man years of proprietary code. I asked for an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) -- a _minimal_, yet _complete_, _example_ that can serve as a standin to _verify_ or reproduce the issue.

Otherwise, we left with banal generalities
- I have worked for 20 years with QuantLib and RQuantLib and it is _expensive_ C++ code that still takes "too long" to compile even on decent machines
- Whether you Rcpp there or not makes little difference as the code is already 'expensive'
- Rcpp packages such as the recent-ish RcppSpdLog are also expensive as spdlog (and fmt) do a lot of heavy compile-time lifting; RcppSimdJson is similar
- Yet you can have 'light' C++ that near C code, look for example at my package tidyCpp that aims to be a skinny and lightweight wrapper on the C API of R

Lastly, concerning `ccache`, I wrote something [here on my blog](http://dirk.eddelbuettel.com/blog/2017/11/27/) and I will allow myself to copy the main chart in full:

![image](https://user-images.githubusercontent.com/673121/114280826-c32b3b80-9a00-11eb-982a-6a0d34781d0c.png)

If you google for my name along with `ccache` you will probably also find a few StackOverflow posts.

**Comment by kevinushey** [comment]
`Rcpp::sourceCpp()` with a sample file makes the issue more clear:

```
> Rcpp::sourceCpp("~/scratch/abc.cpp", verbose = TRUE)

Generated extern "C" functions 
--------------------------------------------------------


#include <Rcpp.h>
// timesTwo
int timesTwo(int x);
RcppExport SEXP sourceCpp_1_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}

Generated R functions 
-------------------------------------------------------

`.sourceCpp_1_DLLInfo` <- dyn.load('/private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp0G37zl/sourceCpp-x86_64-apple-darwin17.0-1.0.6/sourcecpp_93a61a940be3/sourceCpp_2.so')

timesTwo <- Rcpp:::sourceCppFunction(function(x) {}, FALSE, `.sourceCpp_1_DLLInfo`, 'sourceCpp_1_timesTwo')

rm(`.sourceCpp_1_DLLInfo`)

Building shared library
--------------------------------------------------------

DIR: /private/var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T/Rtmp0G37zl/sourceCpp-x86_64-apple-darwin17.0-1.0.6/sourcecpp_93a61a940be3

/Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB -o 'sourceCpp_2.so' 'abc.cpp' 
clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I"/Users/kevin/Library/R/4.0/library/Rcpp/include" -I"/Users/kevin/scratch" -I/usr/local/include   -fPIC  -g -O3 -Wall -pipe -mtune=native -Wno-unused-local-typedef -I/usr/local/opt/openssl/include -Wno-unused-variable -c abc.cpp -o abc.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/opt/openssl/lib -o sourceCpp_2.so abc.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation

> timesTwo(42)
[1] 42
```

In other words, the auto-generated code used during compilation relies on Rcpp classes, and so Rcpp headers must be included.

**Comment by eddelbuettel** [comment]
I am going to close this now.  We can reopen it if something reproducible, measurable and actionable is posted.  Thanks for your understanding.
