### ISSUE TITLE
Link C++ external library

### ISSUE THREAD

**Issue by xianglinZ** [RcppCore/Rcpp#1170]
Hello, I want Rcpp to link external libraries for C++ like eclipse or vscode in the environment of rstudio. How to deal with it? I don't seem to find a suitable answer, thank you.

**Comment by eddelbuettel** [comment]
That question is oddly worded. Eclipse or VS Code are IDES, not libraries.  Both have long been used by Rcpp users for development and there are add-ons.

Please see [the Rcpp FAQ](https://cloud.r-project.org/web/packages/Rcpp/vignettes/Rcpp-FAQ.pdf) as a start, plus maybe the more recent [libraries vignette](https://cloud.r-project.org/web/packages/Rcpp/vignettes/Rcpp-libraries.pdf) if this is about working with libraries rather than iDEs.

I think we can close this now, if you have an actual issue please feel free to reopen preferably with a reproducible example.

**Comment by xianglinZ** [comment]
Sorry, my spoken English is very poor. I rely on translation software to communicate with you. I understand what you said. In fact, what I want to ask is how to introduce C++ external packages like other IDEs. For example, I cloned one on github C++ package, I want to use Rstudio to compile. How will I do it.

**Comment by xianglinZ** [comment]
Thank you very, very much, but maybe I still haven't expressed it clearly. I tried to find the answer in the location you listed, but it doesn't seem to work for me. What I hope is to use other open source c++ packages on github in r. , It’s okay, in short, thank you very much for your reply, I will look for the answer I want to get, thank you for your reply during your busy schedule.

**Comment by eddelbuettel** [comment]
With all do respect, Rcpp has had over the years 50+ million downloads.   We simply cannot do one-on-one tutorials _here in an issue ticket_ as that would be an abuse of the system used to discuss actuall defects or improvements.

As I said, *please* use existing resources.  My home page links to a page of talks and presentations I have given, and you will find Rcpp intros all the way from one hour to three hours to one day and (twice) two full days.  You will find your answer there.

We also have a mailing list where other users will help you.  Please do use those resources.  Links below.

https://cranlogs.r-pkg.org/badges/grand-total/Rcpp

https://dirk.eddelbuettel.com/presentations.html

**Comment by xianglinZ** [comment]
Thank you and best wishes to you.
