### ISSUE TITLE
GCC auto-parallelization flag

### ISSUE THREAD

**Issue by waynelapierre** [RcppCore/Rcpp#1178]
Does Rcpp have a plugin to add the GCC auto-parallelization flag -ftree-parallelize-loops?

**Comment by eddelbuettel** [comment]
You can answer that question with a simple grep in our sources, or, if don't have them checked out, via a GitHub search.  But in short the answer is no, not currently.   Have you demonstrated that the flag helps with all or many kind of loops?  If so, did you document that somewhere?   If that's the case feel free to reopen, otherwise I will close this now.  

As I asked in #1179, please consider the mailing list for such questions.
