### ISSUE TITLE
Problem with gfortran macOS Ventura

### ISSUE THREAD

**Issue by silviacolumbu** [RcppCore/Rcpp#1246]
Hi,

I have updated my mac to Ventura 13.2 and I'm not able to run Rcpp. When I try to compile a cpp file through sourceCpp I get the following errors:

ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.6.0/12.0.1'
ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sourceCpp_2.so] Error 1

I tried to install gcc to provide a new version of gfortran but without fixing the problem. Do you have some suggestions?

Thank you

**Comment by eddelbuettel** [comment]
I can only point you to [R on macOS](https://mac.r-project.org/), I am not a macOS user myself.  However, there are numerous macOS users among the Rcpp users so maybe someone else can pipe in.

**Comment by eddelbuettel** [comment]
I am closing this as it is not really an Rcpp issue -- Rcpp does not use Fortran.  I do feel sorry for the macOS users though; it was good when we had concise and up-to-date information by @coatless because apparently neither [a two-trillion dollar company](https://www.google.com/finance/quote/AAPL:NASDAQ) nor the [R Core team member](https://mac.r-project.org/) can do so in a way that normal humans understand.
