### ISSUE TITLE
Memory management questions

### ISSUE THREAD

**Issue by pierreblavy2** [RcppCore/Rcpp#1266]
References and raw pointers are not handled corectly by Rcpp. 

Here is an example, with a class that implements a counter to track living objects. In this example, the ref function returns a refecence to `*this`, but in a real case, we have the exact same problem for any reference on something **owned** by Test like for example the next Node* for a linked list.

We also do have the exact same problem when we return pointers that are not owned by the caller, which is most of the time the case in cpp for raw pointers, as pointers owned by the caller should be returned as [[nodiscard]] unique_ptr.

```
// --- test.cpp ---

#include <Rcpp.h>
struct Test{
  static int count;

   Test(){++count; Rcpp::Rcout<<"cstr " << count <<std::endl; }
  ~Test(){--count; Rcpp::Rcout<<"dest " << count <<std::endl; } 
  
  Test & ref(){return *this;} 
};
int Test::count = 0;


#include <Rcpp.h>
using namespace Rcpp;

RCPP_EXPOSED_CLASS(Test);

RCPP_MODULE(test) {
  class_<Test>("Test")
  .constructor()
  .method("ref", &Test::ref ) 
;
}
```

```
#--- test.R ---
library(Rcpp);
sourceCpp("R_libs/test.cpp");
a = new(Test);
  # cstr 1, as expected
b=a$ref();
 # prints nothing, as expected
rm(b);gc();
 # dest 0 : WRONG deleting a refecence should do nothing
rm(a);gc()
 # dest -1 : should be ok if the previous line didn't delete when it should not
```

# Ideas to fix this bug :
I'm unsure about this part but I think it should be managed to an other level of indirection.

* When the wrapped value is a value, wrap it as a unique_ptr
* When the wrapped value is a reference, wrap it as a smart pointer with a custom deleter that does nothing like std::reference_wrapper
* As the wrapped value is a smart pointer (like unique_ptr, shared_ptr, std::ref, or whatever) , rely on the smart pointer mechanic to handle the object. 
* Make the R code to work the same way regardless of the wrapped pointer type.
* A temporary mitigation can be to add some static_assert to prevent wrapping references and pointers, as it doesn't work as is.

**Comment by eddelbuettel** [comment]
Thanks for taking the time to write an issue.  Rcpp is an R package using the .Call() interface using SEXP ("S Expression Pointers") so there are limits to what can be done here.  If you have an idea to fundamentally improve upon this somewhat time-test solutions we'd be all ears and would welcome a PR or issue demonstrating it.

**Comment by eddelbuettel** [comment]
Also, as an addendum, your example uses Rcpp Modules which are one of several ways to work with Rcpp.  Modules offers a few nice features, but also have limits ... and in essence have not seen much development in close to a decade.

R offers external pointers, for Rcpp these become the XPtr object.  You could play with those but because R itself is garbage collected in it is fairly easy to get entangled when mixing R object with C++ reference counted objects.  But you may well have fresh ideas so I encourage to explore and express them.

**Comment by Enchufa2** [comment]
I don't see anything wrong about how the Rcpp module manages this. The `ref` method returns a `const` reference, but as soon as we try to return it to R, we cannot ensure that property anymore, so it is copied [here](https://github.com/RcppCore/Rcpp/blob/71e64b0513ce358535575dccc4fdf5c841701619/inst/include/Rcpp/internal/wrap.h#L759) to return a external pointer. The copy however does not increment the counter, so the `Test` class is missing a copy method which should do that.

**Comment by Enchufa2** [comment]
Actually, we _could_ define a `wrap_dispatch` without the `const` specifier, and then return just the pointer to the reference. But then this would create two different S4 objects referencing the same pointer, and I don't know whether this could backfire.

**Comment by pierreblavy2** [comment]
@eddelbuettel

I'm not really good for understanding the R arcana, but I'll be very happy to help and improve how object are managed. I'll be very happy to have some information about. 
- how the module magic works to expose the stuff declared in .method as callable in R? If I write some kind of wrapper for references or not owning pointer, it must be callable in R the same way the referenced or the pointed class is. I'm sorry but I was unable to find some documentation about it, so all help is welcomed.
- how do we define a  SEXP pointing to a custome object?
- how do we define a custom destructor for a SEXP ?

I've also found some class called XPtr, that may be helpfull. I can wrap things to return a XPtr<Test> instead of a Test* but then, there is no method attached to it in R, so I cannot use it. I also don't know what XPtr does or how it manages its memory.



@Enchufa2.
Not all classes are copyable, here I don't want a Test(const Test&) function.
I may have added : 
Test(const Test&)=delete;

As Test is accessed trough a reference, it's not supposed to be copied.

The fact R is garbage collected is not the main issue. The garbage collection may change WHEN the actual deletion occurs (so objects are not destroyed at the end of their scope, or when rm is called, but at some point in the future). A garbage collector actually breaks RAII, makes ressource management hell (typically when the code branches or throw exception) but it must not change HOW objects are deleted. Here we do have a double delete error, because delete is called on a not owning pointer (or on a reference), not because the actual deletion happens at an unexpected time.

**Comment by eddelbuettel** [comment]
@pierreblavy2 I have been at this for 15+ years and have written quite a bit about it.  We also had good luck with the update so there over 2600 packages using Rcpp at CRAN alone, and you can search them all (!!) (plus actually any ones that once were on CRAN and are no longer) with the GitHub 'cran' organization:   https://github.com/cran/

I also don't quite have the time and bandwidth now to discuss R internals here -- it is not the best place.  But I don't want to send you away:  I was just looking to `unique_ptr` in the context of `Rcpp::XPtr` (and think it is 'nope') but there is possibly work to be done.  (And I do work with zero copy memory _outside of R_ right now for a work project.)  But R is tricky, and it "takes some getting used to" and it is NOT the same as plain C++.  Keep at it please, I think you will find it useful.

**Comment by pierreblavy2** [comment]
I'm a little bit lost, but thank a lot for your help !

**Comment by eddelbuettel** [comment]
That is par for the course.  There is _a lot_ here but you cannot do extensions modules for R / reason about how R should do things without knowing a little about R.   We all started with the (somewhat hard to digest, but comprehensive) [Writing R Extension](https://rstudio.github.io/r-manuals/r-exts/) (plus maybe the sibbling 'Language' and 'Internals' manuals). Many good nuggets are in Section 5 and below.

**Comment by Enchufa2** [comment]
@pierreblavy2 Dirk's advice will save you a lot of time: before trying to implement fancy things in C++, please take a look at the R internals and how the interface looks like. Some quick hints:

- Everything in R core is a `SEXP`, which is a lightweight self-describing structure.
- One of this `SEXP`s is the `EXTPTRSXP`, or external pointer. This just holds a void C pointer that could be anything. 
- So forget about unique pointers, shared pointers, and other fancy things: whenever you want to export some object to the R side, that must be a void C pointer.
- The other piece of the puzzle that Rcpp provides to seamlessly work with external pointers is the `XPtr` class. This allows you not only to cast them to the proper class and use them, but also to register the removal of that object when the external pointer is no longer referenced in any place (so it is similar to a shared pointer).

Now, you are looking at this issue from the perspective of your particular use case, where you have a long-lived object that takes care of everything else, so you don't want the R garbage collector to fiddle with your objects, which is fine. But that's not the only use case, and given how old Rcpp is and the number of packages using it, I'd confidently say it's not the most common case. That's why the `XPtr` constructor has a default `bool set_delete_finalizer = true`. Otherwise, we would see _tons_ of memory leaks in the dependent packages, because developers typically create objects, export them to R and expect that R takes care of cleaning things up when they don't use them anymore.

You seem to have a special advanced use case. [So do I](https://r-simmer.org/). My recommendation would be to forget about modules, and work with `XPtr` directly. In my code, you'll find examples of [long-lived objects](https://github.com/r-simmer/simmer/blob/cb9b0651d1c7b6fa364fee708407ec6b4619a2d3/src/simulator.cpp#L27) that are properly garbage-collected when the reference is lost in the R session, as well as [references to nodes in a linked list](https://github.com/r-simmer/simmer/blob/cb9b0651d1c7b6fa364fee708407ec6b4619a2d3/src/activity.cpp#L465) that need to be left alone (note the second argument set to `false`).

Modules are much more complicated, and have several limitations. That said, once you are familiar with `XPtr`s, if you feel like there's a way to improve modules, contributions are most welcome, and we can help you. :)

**Comment by pierreblavy2** [comment]
Thank a lot !
I'll try to follow your advice.  I still have things to learn, but it's getting clearer with the link you've posted.

**Comment by eddelbuettel** [comment]
Also:  "Simple works."  I keep forgetting where I did this but I do have a package (or more) where I casually construct a C++ class as I like, use it as a singleton (hey, we R know is not multithread) accessible from a static pointer and then use Rcpp for helpers functions to
- allocate / init / setup
- setter and getter as I need it
- wind it down

The R 'foreign function interface' is robust and time tested. There are things it does, and things is doesn't.  But it is the only interface we have so we play the hand we've been dealt, not the one we dream we had.
