### ISSUE TITLE
Add support for check.names

### ISSUE THREAD

**Issue by maxfirman** [RcppCore/Rcpp#1273]
I have a requirement to be able to return a `data.frame` from Rcpp with `check.name=FALSE` to prevent column name sanitisation. Is this something you would be happy to have added to Rcpp /  would you accept it as a PR?

**Comment by eddelbuettel** [comment]
That sounds reasonable, and I guess you can follow the pattern of how `strings_as_factors` is treated.

Or, and I am just thinking out loud here, because it is a rare enough need that maybe we do not extend the class, you simply wrap this locally?  Here is a minimal example modifying one from [RcppExamples](https://github.com/eddelbuettel/rcppexamples):

#### Code

```c++

#include <Rcpp/Lightest>

// [[Rcpp::export]]
Rcpp::List DataFrameExample() {

  // access each column by name
  std::vector<int> a{1,3,5};
  std::vector<double> b{1.1, 3.3, 5.5};

  return Rcpp::List::create(Rcpp::Named("bad name") = a,
                            Rcpp::Named("123") = b);
}

/*** R
x <- DataFrameExample()
x
data.frame(DataFrameExample(),check.names=FALSE)
*/
```

#### Output

````r
> Rcpp::sourceCpp("/tmp/rcppdfex.cpp")

> x <- DataFrameExample()

> x
$`bad name`
[1] 1 3 5

$`123`
[1] 1.1 3.3 5.5


> data.frame(DataFrameExample(),check.names=FALSE)
  bad name 123
1        1 1.1
2        3 3.3
3        5 5.5
> 
```

Team Rcpp:  Any views on narrow versys wider?  We can clearly do this, but I am not sure if it is wise to chase too many options.  Then again, adding one every ten or so years is not bad :)

**Comment by eddelbuettel** [comment]
Yes there are two posts at the Rcpp Gallery going the same directorion.

**Comment by maxfirman** [comment]
I have changed my function return type to `SEXP` instead of `DataFrame` and set `class` and `row.names` attributes as you suggested. The column names are no longer sanitised which is exactly what I want. 

Thanks very much for your help, it is greatly appreciated. Please feel free to close the issue.

**Comment by eddelbuettel** [comment]
Perfect, will close.
