### ISSUE TITLE
compileAttributes() confused by inline comments in C++ argument-list

### ISSUE THREAD

**Issue by fabian-s** [RcppCore/Rcpp#138]
This works, obviously:

```
library(Rcpp)
sourceCpp(code = "
    // [[Rcpp::depends(Rcpp)]]
    #include <Rcpp.h>

    using namespace Rcpp ;
    using namespace std ;

    // [[Rcpp::export]]
    double vecsum(NumericVector vec, 
                  double offset){
        double sum = std::accumulate(vec.begin(),vec.end(), offset) ;
        return sum ;
    }")
```

but adding inline comments to the argument list of the function like this

```
sourceCpp(code = "
    // [[Rcpp::depends(Rcpp)]]
    #include <Rcpp.h>

    using namespace Rcpp ;
    using namespace std ;

    // [[Rcpp::export]]
    double vecsum_inlinecomments(NumericVector vec,  //some vector
                  double offset) // some offset
    {
        double sum = std::accumulate(vec.begin(),vec.end(), 0.0) ;
        return sum ;
    }", verbose=TRUE)
```

leads to `compileAttributes` generating this:

```
Generated extern "C" functions 
--------------------------------------------------------


#include <Rcpp.h>

RcppExport SEXP sourceCpp_40092_vecsum_blockcomments(SEXP vecSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP );
        Rcpp::traits::input_parameter< /* some vector */                   double >::type offset(offsetSEXP );
        double __result = vecsum_blockcomments(vec, offset);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}

[...]
/usr/lib/R/bin/R CMD SHLIB -o 'sourceCpp_81766.so' 'file121b9ac731c.cpp' 
g++ -I/usr/share/R/include          -I"/home/fabians/R/x86_64-pc-linux-gnu-library/3.0/Rcpp/include"    -fpic  -O3 -pipe        -c file121b9ac731c.cpp -o file121b9ac731c.o
file121b9ac731c.cpp: In function ‘SEXPREC* sourceCpp_1255_vecsum_inlinecomments(SEXP, SEXP)’:
file121b9ac731c.cpp:26:60: error: template argument 1 is invalid
file121b9ac731c.cpp:27:9: error: ‘__result’ was not declared in this scope
[...]
```

Apologies for wasting everybody's time if inline comments like that are frowned upon in C++, I'm not a very good programmer and don't know much about good C++ style, BUT since the code compiles fine until you add the `[[Rcpp::export]]` attribute, this seems like very undesirable behavior to me.

**Comment by gitclem** [comment]
For the record (and for anyone encountering this), I got the obscure error in version 1.0.0 of Rcpp:


```
In file included from /usr/local/lib/R/site-library/Rcpp/include/Rcpp.h:27:0,
                 from die.cpp:1:
/usr/local/lib/R/site-library/Rcpp/include/RcppCommon.h:139:20: error: expected ‘,’ or ‘...’ before ‘extern’
 #define RcppExport extern "C" attribute_visible
                    ^
die.cpp:16:1: note: in expansion of macro ‘RcppExport’
 RcppExport SEXP sourceCpp_29_body_to_linear_cpp(SEXP commentSEXP) {
 ^
die.cpp:24:1: error: expected ‘)’ at end of input
 }
 ^
die.cpp:24:1: error: expected initializer at end of input

```

**Comment by eddelbuettel** [comment]
What does it have to do with this 4 1/2 year old ticket, which has been fixed?

If you have a _new_ file it with a _reproducible_ example.  The snippet you posted is close to useless.

**Comment by gitclem** [comment]
Since I doubt anyone will fix this, I'm adding to the ticket, because the error msg is now different and really obscure. (I tried searching for this particular error but couldn't find it.) It took me a while to track it down.  I thought it would be useful in case somebody encounters this same misfeature that has a different err msg.

I can see that it's not worth fixing, but it is useful to know about.

**Comment by eddelbuettel** [comment]
You are not making any sense whatsoever.  The ticket over fifty months old, we probably made 25 releases since then.  Rcpp works and is downloaded over 800,000 times each month.  You are making unsubstantiated comments ("does not work", "will not get fixed") here in what I must consider a totally unrelated issue.

Please browse some current issue tickets to get a feel for _useful_ error reports.  We need input that produces an error.  You have not supplied this, and I can only suspect you are using Rcpp in an incorrect way.  The Rcpp Introductions and the Rcpp FAQ may help.

I am locking this issue now, and I managed to not forget, plan to delete your two posts here (as well as mine).
