### ISSUE TITLE
const versions of row and column for Matrix

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#200]
There only are these non const versions: 

```
    inline Row row( int i ){ return Row( *this, i ) ; }
    inline Column column( int i ){ return Column(*this, i ) ; }
```

so we can't call `row` or `column` on a `const` Matrix.

**Comment by dcdillon** [comment]
I have written code that I believe addresses this issue, however, due to some underlying issues specifically with `Rcpp::Vector::const_iterator` it got a little bit more complicated (and intrusive) than expected.

To solve the initial issue of no const versions of `row()` and `column()` being available in `Matrix` I did the following:
* Create `ConstMatrixColumn` and `ConstMatrixRow` classes
  * These are just like their non-const brothers, except they only provide `const_iterators` to traverse them.
  * They still inherit from `VectorBase`.  After careful analysis of this class, it is const safe so there needn't be any change here.  This is good because `VectorBase` is used extensively throughout the codebase.
* Add `ConstMatrixColumn column(int i) const` and `ConstMatrixRow row(int i) const` functions to the `Matrix` class.
* Add `ConstMatrixColumn operator()(internal::NamedPlaceHolder, int i) const` and `ConstMatrixRow operator()(int i, internal::NamedPlaceHolder) const` functions to the `Matrix` class.

Now this all works wonderfully except for the fact that the `Vector::const_iterator` is so very different from its counterpart `Vector::iterator`.  

`Vector::iterator` has specializations for well-known types that are instantiations of `internal::Proxy_Iterator` as shown below (from Rcpp/vector/proxy.h).

```c++
        template <int RTYPE> struct proxy_based_iterator{
                typedef ::Rcpp::internal::Proxy_Iterator< typename r_vector_proxy<RTYPE>::type > type ;
        } ;
        template<> struct r_vector_iterator<VECSXP> : proxy_based_iterator<VECSXP>{} ;
        template<> struct r_vector_iterator<EXPRSXP> : proxy_based_iterator<EXPRSXP>{} ;
        template<> struct r_vector_iterator<STRSXP> : proxy_based_iterator<STRSXP>{} ;
```

`Vector::const_iterator` was merely defined by (from Rcpp/vector/proxy.h):

```c++
        template <int RTYPE>
        struct r_vector_const_iterator {
                typedef const typename storage_type<RTYPE>::type* type ;
        };
```

It had no specializations and was not a full-featured iterator like `Vector::iterator` was.  This led to some problems with the unit tests passing.

My solution to the problem (which I believe only adds functionality) was to create a new class called `internal::Const_Proxy_Iterator` which is identical to `internal::Proxy_Iterator` in every way except that `operator*()` and `operator->()` return `const` references and pointers respectively.  Then simply adding the following to Rcpp/vector/proxy.h gives us a full-featured and appropriately specialized `Vector::const_iterator`.

```c++
        template <int RTYPE> struct proxy_based_const_iterator{
                typedef ::Rcpp::internal::Const_Proxy_Iterator< typename r_vector_const_proxy<RTYPE>::type > type ;
        } ;
        template<> struct r_vector_const_iterator<VECSXP> : proxy_based_const_iterator<VECSXP>{} ;
        template<> struct r_vector_const_iterator<EXPRSXP> : proxy_based_const_iterator<EXPRSXP>{} ;
        template<> struct r_vector_const_iterator<STRSXP> : proxy_based_const_iterator<STRSXP>{} ;
```

All of these changes (with the addition of unit tests for the `const` variants of `Matrix::row()` and `Matrix::column()`) yield functional `const` access to `Matrix` rows and columns as well as a passing `R CMD check`.

While this is a rather large change (i.e. the definition of `const_iterator` is significantly different) I believe that it only adds functionality and shouldn't (famous last words) break any user's implementations.  That is to say, because the old implementation of `const_iterator` was so bare bones, replacing it with a more full-featured implementation should be both desirable and non-intrusive.

Anyhow, that's where my code is at.  Please let me know if you are interested in a PR for this.

**Comment by dcdillon** [comment]
This issue is commited and merged I believe. Feel free to close.

**Comment by eddelbuettel** [comment]
Even before PR #405 is finalized?

**Comment by dcdillon** [comment]
gah....i posted in the wrong issue.

**Comment by Thell** [comment]
Fantastic! Looking forward to the next release. hmmm, working with LogicalMatrix?
