### ISSUE TITLE
operator/ needs to handle the case of division by 0

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#22]

**Comment by coatless** [comment]
This issue seems to have been resolved long before it was posted to Git. 

The governing header ([/inst/include/Rcpp/sugar/operators/divides.h](https://github.com/RcppCore/Rcpp/blob/96f36a1706ebba3289b247690052f7b215b0dfb3/inst/include/Rcpp/sugar/operators/divides.h) appears to support the calculation with appropriate R fails:

x / 0,  x != 0

```r
 c(5,2) / 0
# [1] Inf -Inf
```

```r
str( Rcpp::evalCpp( "NumericVector::create(5,-2)/0" ) )
```

Output:
```
num [1:2] Inf -Inf
```

0 / 0 

```r
 c(0,0) / 0
# [1] NaN NaN
```

```r
str( Rcpp::evalCpp( "NumericVector::create(0,0)/0" ) )
```

Output
```
num [1:2] NaN NaN
```

Please close. (Tagging #506)
