### ISSUE TITLE
sorting in CharacterVector is not equal to sorting in R

### ISSUE THREAD

**Issue by emiliotorres** [RcppCore/Rcpp#251]
Lexicographic order in CharacterVector differs from the result obtained in R. See example.
Is this result the expected behaviour?
Thank you!

```
#include <Rcpp.h>
using namespace Rcpp ;

// [[Rcpp::export]]
CharacterVector sortcpp(CharacterVector x) {
  x.sort();
  return x;
  }

/*** R
     x <-c("B", "b", "c","A","a")
     sort(x)    ## "a" "A" "b" "B" "c"
     sortcpp(x) ## "A" "B" "a" "b" "c"
*/
```

**Comment by emiliotorres** [comment]
The character comparison in Rcpp is made by the  `strcmp` C function. R uses a `Scollate` function that depends on `locale`. I am not sure if it is possible to redefine the `StrCmp` function using `Scollate` instead of `strcmp`.


In `Rcpp/inst/include/Rcpp/internal/NAComparator.h`:
```
inline int StrCmp(SEXP x, SEXP y) {
if (x == NA_STRING) return (y == NA_STRING ? 0 : 1);
if (y == NA_STRING) return -1;
if (x == y) return 0; // same string in cache
return strcmp(char_nocheck(x), char_nocheck(y));
}
```

In  `r-source/src/main/sort.c`
```
static int scmp(SEXP x, SEXP y, Rboolean nalast)
{
if (x == NA_STRING && y == NA_STRING) return 0;
if (x == NA_STRING) return nalast ? 1 : -1;
if (y == NA_STRING) return nalast ? -1 : 1;
if (x == y) return 0; /* same string in cache */
return Scollate(x, y);
}
```
In  `r-source/src/main/util.c`
```
int Scollate(SEXP a, SEXP b)
{
if (!collationLocaleSet) {
collationLocaleSet = 1;
#ifndef Win32
if (strcmp("C", getLocale()) ) {
#else
const char *p = getenv("R_ICU_LOCALE");
...
```

**Comment by kevinushey** [comment]
This one is quite thorny, as R does not export `Scollate`. I think the best we can do is try to mimic what `Scollate` does with our own copy, but that is ugly and error prone especially if `Scollate` were to change.

**Comment by coatless** [comment]
Last entry before I send a PR later tonight.

Sixth entry in _Section: Known Issues_

Title: Lexicographic Order of String Sorting Differs Due to Capitalization

Text:

Comparing strings within \R hinges on the ability to process the locale or native-language environment of the string. In \R, there is a function called \code{Scollate} that performs the comparison on locale. Unfortunately, this function has not been made publicly available and, thus, Rcpp does \textit{not} have access to it within its implementation of \code{StrCmp}. As a result, strings that are sorted under the \code{.sort()} member function are ordered improperly. Specifically, if capitalization is present, then capitalized words are sorted together followed by the sorting of lowercase words instead of a mixture of capitalized and lowercase words. The issue is illustrated by the following code example:

```cpp
#include <Rcpp.h>

// [[Rcpp::export]]
Rcpp::CharacterVector sortcpp(Rcpp::CharacterVector x) {
  x.sort();
  return x;
}

/*** R
x <- c("B", "b", "c","A","a")

# Using R's sort
sort(x)    
## "a" "A" "b" "B" "c"

# Using Rcpp's sort
sortcpp(x) 
## "A" "B" "a" "b" "c"
*/
```

**Comment by coatless** [comment]
@eddelbuettel: This issue can now be closed.
