### ISSUE TITLE
Rcpp hanging on recursion

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#264]
By email, and with details [in this gist](https://gist.github.com/jorgemarsal/bb880745ada2a5a9b5d2).  I followed up, and this happens with all versions of 0.11.* -- but as stated only on the older compiler.

**Comment by jorgemarsal** [comment]
I've just copied the gist below so we have all the info in this ticket.

## The issue
In some compiler versions (e.g. GCC 4.6.4 in Ubuntu) when compiling with `-rdynamic` two functions with the same name (e.g. `dataptr` defined both in `routines.h` and `barrier.cpp`) are placed in the dynamic symbol table. Subsequently When we do `R_GetCCallable("Rcpp", "dataptr")` we get the wrong function at runtime.

When Rcpp registers `dataptr` it means this function (in `barrier.cpp`):

    // [[Rcpp::register]]
    void* dataptr(SEXP x){
        return DATAPTR(x);
    }

However at runtime we're getting this other one (in `routines.h`):

    inline void* dataptr(SEXP x){
        typedef void* (*Fun)(SEXP) ;
        static Fun fun = GET_CALLABLE("dataptr") ;
        return fun(x) ;
    }

This results in infinite recursion (because `dataptr` in `routines.h` is calling itself). The infinite recursion produces either a segfault (stack overflow) or hangs the process when the compiler does tail call optimization and the infinite recursion get transformed into an infinite loop.


To show the issue letâ€™s create a simple test program:

    #include <Rcpp.h>
    #include <RInside.h>

    #include <iostream>

    int main() {
        RInside R;
        int size = 38;
        Rcpp::RawVector raw(size);
        std::cout << "done" << std::endl;
        return 0;
    }

Letâ€™s compile:

    g++-4.6 -I/data/R-3.1.2/include -I/usr/local/lib/R/site-library/RInside/include/ -I/usr/local/lib/R/site-library/Rcpp/include/ -I/usr/share/R/include/ -O2 -g -rdynamic -o rcpphang-4.6 rcpphang.cpp -lR -lRblas -lRInside -L/usr/local/lib/R/site-library/RInside/lib/ -L/data/R-3.1.2/lib
    g++-4.8 -I/data/R-3.1.2/include -I/usr/local/lib/R/site-library/RInside/include/ -I/usr/local/lib/R/site-library/Rcpp/include/ -I/usr/share/R/include/ -O2 -g -rdynamic -o rcpphang-4.8 rcpphang.cpp -lR -lRblas -lRInside -L/usr/local/lib/R/site-library/RInside/lib/ -L/data/R-3.1.2/lib

If we take a look at the symbol tables we can see that `Rcpp.so` has the right `dataptr`:
    
    $ nm --dynamic /usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so|grep dataptr
      000000000003c8e0 T _Z7dataptrP7SEXPREC

However our programs have extra symbols that shouldn't be there. In this case GCC 4.6 is exporting 3 extra symbols for `dataptr` and GCC 4.8 is exporting 2 extra symbols:

    $ nm --dynamic  rcpphang-4.6|grep dataptr
    0000000000402b50 W _Z7dataptrP7SEXPREC
    0000000000604698 u _ZGVZ7dataptrP7SEXPRECE3fun
    00000000006046a0 u _ZZ7dataptrP7SEXPRECE3fun
    $ nm --dynamic  rcpphang-4.8|grep dataptr
    0000000000604688 u _ZGVZ7dataptrP7SEXPRECE3fun
    0000000000604680 u _ZZ7dataptrP7SEXPRECE3fun

If we run the programs the one compiled with GCC 4.8 works fine but the one compiled with GCC 4.6 hangs.

## Possible fix

One possible workaround is to define the functions in `routines.h` with visibility `hidden` like this:

    inline __attribute__ ((visibility ("hidden"))) void* dataptr(SEXP x){
      
If we compile again (after adding `hidden`) the result is:

    nm --dynamic  rcpphang-4.8|grep dataptr
    <empty>
    nm --dynamic  rcpphang-4.6|grep dataptr
    <empty>

In this case `dataptr` is not being exported and if we run the programs both finish sucessfully.

## Conclusion

This is a really tricky issue because it only appears when compiling with certain versions (e.g. GCC 4.6.4 in Ubuntu) and certain flags (`-rdynamic`).

Although the bug is only triggered under those conditions we believe this is an Rcpp bug and we should fix it there.

We're not the only ones we've seen this:
+  [Rcpp issue #78](https://github.com/RcppCore/Rcpp/issues/178)
*  [Distributed R pull request #5](https://github.com/vertica/DistributedR/pull/5)

We're happy to discuss this. Let us know if you need more clarifications or something doesn't make sense. If you're comfortable with the `hidden` workaround we can send you a pull request that does this for the 28 exported functions. It only changes `routines.h`. We've run `R CMD check` with the `hidden` fix and everything works fine.

**Comment by jorgemarsal** [comment]
In my tests (Ubuntu 14.04 LTS) the issue appears only with GCC 4.6. However some coworkers have seen the same issue in 4.8 and 4.4 as well. They use CentOS. The `hidden` fix proposed above fixes the issue in their systems as well, without unwanted side effects.

**Comment by eddelbuettel** [comment]
Thanks for copying it over -- much easier indeed.   

Would we want to `#ifdef` the use of `inline __attribute__ ((visibility ("hidden")))` on the compiler being g++?  I have never needed this on Linux; I have vague memories from it being needed with visual c++ on that windoze and I still shudder thinking about that.  

@jjallaire, @kevinushey : any insight?

**Comment by jjallaire** [comment]
We could use these macros from R to get it wherever it's available (it looks like they already do the checking during R configuration):

https://github.com/wch/r-source/blob/master/src/include/R_ext/Visibility.h

**Comment by eddelbuettel** [comment]
Good point. 

I always hated those (or, rather, the "hidden" variant) as I found they helped "them" to seal off things in the API we could otherwise poke a stick at :)

I guess we could prefix the 28 functions in routines.h with `attribute_hidden` and run a new regression test.  I am due one anyway after all your changes ;-)

**Comment by jjallaire** [comment]
Yeah, I was foiled by hidden originally when I ported the earliest versions
of RStudio from Linux to the Mac (the macros used to no-op on Linux but
actually do something on the Mac). Had to re-work a bunch of stuff then and
again in the undocumented API purge of R 3.0 :-)


On Mon, Feb 23, 2015 at 4:50 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
And just to be very plain, these macros still need this compiler switch, correct?

```{.bash}
edd@max:~$ grep visibility /etc/R/Makeconf 
C_VISIBILITY = -fvisibility=hidden
F77_VISIBILITY = -fvisibility=hidden
edd@max:~$ 
```

**Comment by jjallaire** [comment]
Yes, I believe they won't actually be enforced without that.

On Mon, Feb 23, 2015 at 5:03 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
@jorgemarsal I created a new branch https://github.com/RcppCore/Rcpp/tree/bugfix/visibility-hidden
It tests out okay in a normal `R CMD check --as-cran ...`; I am now running a full reverse-depends check against all CRAN packages using this.  I expect this to pass.   Could you also run tests at your end to see whether this correctly applies the suggested fix?

(@jjallaire: btw, I did run a rev-dep check for RcppArmadillo yesterday morning and 107 out of those 109 passed with 2 known [old, not ours] issues -- that covered a bunch of the recent PRs. Looking good :+1:   ;-)

**Comment by jorgemarsal** [comment]
We tested on our end and it works fine. Thanks for the quick fix!

**Comment by eddelbuettel** [comment]
Great, thanks.    Your carefully argued bug report helped a lot.

I had to stop my test run, and turn to re-testing RcppArmadillo, this time without `ccache`.  Rcpp is looking good and has seen a number of updates so we may get to a release in the next couple of weeks.

**Comment by jorgemarsal** [comment]
Sounds good. Thanks!

**Comment by jorgemarsal** [comment]
Hi Dirk,

I've seen the same issue happening again, this time in the Rcpp and Rcpp::internal namespaces.

Program received signal SIGSEGV, Segmentation fault.
0x00007fd7b1567d38 in Rcpp::internal::get_Rcpp_namespace () at /home/jorgem/R/x86_64-unknown-linux-gnu-library/3.1/Rcpp/include/Rcpp/routines.h:95
95	        inline SEXP get_Rcpp_namespace() {

I guess we need to add `attribute_hidden` to these functions as well:
+ type2name
+ enterRNGScope
+ exitRNGScope
+ get_string_buffer
+ get_Rcpp_namespace
+ mktime00
+ gmtime_

**Comment by eddelbuettel** [comment]
Please try the current GitHub version.

**Comment by jorgemarsal** [comment]
I tried with the current GitHub version (cloned today). I'm getting the same issue (infinite recursion) but this time with `Rcpp::internal::get_Rcpp_namespace`. I checked `routines.h` and the functions in the `Rcpp` and `Rcpp::internal` namespaces don't have `attribute_hidden`. I guess we need to add it to those functions as well.

**Comment by eddelbuettel** [comment]
I made the change -- it is currently in a new branch.  It would terrific if you could check that branch.

I'll hold off 0.11.5 for another day til we have this sorted out.

**Comment by jorgemarsal** [comment]
Just tested it and it works fine. Thanks!

**Comment by eddelbuettel** [comment]
Great. Thanks so much for this! 

I am re-running another full test against all reverse dependencies now (and that branch too got merged). Given that, I will probably release later today, and it then takes CRAN a day or two or ... to process as they too check the dependencies, which takes a while for Rcpp.

**Comment by jorgemarsal** [comment]
Sounds good, thanks!
