### ISSUE TITLE
tests for dpq functions

### ISSUE THREAD

**Issue by romainfrancois** [RcppCore/Rcpp#29]
many dpq functions have not been tested yet

**Comment by coatless** [comment]
This issue has been addressed in commit 6a32d4dffbf2d472e3bebfb4f439e453588408ea. Presently, all distributions supported in `Rmath.h` have [a test for p/d/q](https://github.com/RcppCore/Rcpp/blob/master/inst/unitTests/runit.rmath.R). 

**There are no random r*name* tests though.**

As this issue is for p/d/q, please close. (Tagging #506)

**Comment by coatless** [comment]
Sugar testing for `p/d/q` is needed per:

http://stackoverflow.com/questions/38668056/error-building-wrapper-around-rcpp-function

@eddelbuettel  need to reopen ='(

**Comment by eddelbuettel** [comment]
Not sure if it is needed or if that OP is just lost in yonkers.

```r
R>  sum(dbinom(46:54, 100, 0.5))     # see help(dbinom)
[1] 0.631798
R> dbinom(46:54, 100, 0.5)
[1] 0.0579584 0.0665905 0.0735270 0.0780287 0.0795892 0.0780287 0.0735270 0.0665905 0.0579584
R> cppFunction("NumericVector cppdbinom(IntegerVector x, int n, double p, bool l=false) { return dbinom(x, n, p, l); }")
R> sum(cppdbinom(46:54, 100, 0.5))
[1] 0.631798
R> 
```

Looks fine to me.
