### ISSUE TITLE
language objects passed into Function need to be protected

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#305]
Otherwise function calls which introspect on the function arguments (e.g. `match.call()`) will fail.

https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/Function.h#L77-L79
https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/generated/Function__operator.h#L33-L36 (and friends)

**Comment by coatless** [comment]
It seems like initial protection was added to `Function.h` in [ca82a84](https://github.com/RcppCore/Rcpp/blob/ca82a84e892bb6f825d3a4cbde380092caba6425/inst/include/Rcpp/Function.h#L77-L80)

```cpp
SEXP operator()() const {
   Shield<SEXP> call(Rf_lang1(Storage::get__()));
   return Rcpp_eval(call);
}
```

And the initial link was taken from [be5d100](https://github.com/RcppCore/Rcpp/blob/be5d10007170b94c523d0ba0b5d64ff6bc820a29/inst/include/Rcpp/Function.h#L77-L79)
```cpp
SEXP operator()() const {
    return Rcpp_eval( Rf_lang1( Storage::get__()  ) ) ;
}
```

Though, the changes did not propagate out to the [`generated/Function_operator.h`](https://github.com/RcppCore/Rcpp/blob/ca82a84e892bb6f825d3a4cbde380092caba6425/inst/include/Rcpp/generated/Function__operator.h#L33-L36).

Is this something that should be replicated out or can this issue be closed out due to the `Shield<>` protection?

(Tagging #506)

**Comment by eddelbuettel** [comment]
@kevinushey ?

**Comment by kevinushey** [comment]
I think we do need to protect those call objects before evaluation; ie,

```
template <typename T1>
SEXP operator()(const T1& t1) const {
	return Rcpp_eval( Rcpp_lcons( Storage::get__(), pairlist(t1) ) ) ;
}
```

should instead be something like:

```
template <typename T1>
SEXP operator()(const T1& t1) const {
        Shield<SEXP> call( Rcpp_lcons( Storage::get__(), pairlist(t1) ) );
        return Rcpp_eval(call);
}
```

A small reproducible example:

```cpp
// [[Rcpp::plugins(cpp11)]]

#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
SEXP ouch(SEXP defn, SEXP call) {
  Function fn("match.call");
  return fn(defn, call);
}

/*** R
defn <- rnorm
call <- quote(rnorm(1, 2, 3))
match.call(defn, call)
gctorture(TRUE)
ouch(defn, call)
gctorture(FALSE)
*/
```

gives

```
> ouch(defn, call)
 Error in eval(expr, envir, enclos) : invalid 'call' argument 
```

and presumedly that `invalid 'call' argument` error is occurring because the call has been cleaned up.

**Comment by kevinushey** [comment]
it seems like these do need to be protected, but I'm having trouble producing a reproducible example ...

**Comment by kevinushey** [comment]
Hmm, we might be safe because `Rcpp_eval()` wraps and protects the passed-in call objects: 

https://github.com/RcppCore/Rcpp/blob/ca82a84e892bb6f825d3a4cbde380092caba6425/inst/include/Rcpp/api/meat/Rcpp_eval.h#L37-L43

So even if the objects passed to `Rcpp_eval()` aren't protected, `Rcpp_eval()` wraps them in a protected SEXP. In theory, we could run into problems before `Rcpp_eval()` protects those, but I don't think that will happen in practice.
