### ISSUE TITLE
`suppressMessage` fails to suppress `message` called from Rcpp

### ISSUE THREAD

**Issue by kevinushey** [RcppCore/Rcpp#311]
Consider this example:

```cpp
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
void r_message() {
  Function message("message");
  message("Hello!");
}

/*** R
suppressMessages(r_message())
*/
```

The message is not properly suppressed.

I think this is probably due to the exception handling changes done, and moving execution to `R_TopLevelExec`. :(

**Comment by kevinushey** [comment]
I can't recall -- is there a reason why we chose `R_TopLevelExec` over `R_tryEval`? Luke Tierney notes in a thread [here](http://grokbase.com/p/r/r-devel/101ehs5cg7/rd-how-to-call-a-function-from-c):

> The other issue is that what R_tryEval catches is not errors, it is
> longjmp attempts. The vast majority of these will come from attempts
> to pass errors to exiting handlers, but there are other possibilities,
> such as invoking an abort restart (which jumps to top level).

Since we explicitly added this functionality to avoid `longjmp`s perhaps `R_tryEval` is a better choice?

**Comment by kevinushey** [comment]
`R_tryEval` is already just doing an `R_TopLevelExec` so that may not be what we need here...

**Comment by jjallaire** [comment]
It's definitely possible for us to also catch messages. We wrap the
evaluation in withCallingHandlers which AKAIK can also catch messages
(right now it just catches warnings in our code):

https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/api/meat/Rcpp_eval.h#L61-L67

The issue with adding the messages handler is it will put us through
another version mismash debacle. Typically since there is so little code
that changes in our shared library you can run the new headers against old
versions of the shared library (and this is common when packages that use
Rcpp are built on CRAN against the newer version but then run on a user
workstation against the older version). When we introduced this change a
ton of packages "broke" as a result of this and the carnage wasn't over
until everyone had updated to the new Rcpp.

If the way we handle messages can be entirely header-only then we are okay,
but the warnings were handled by adding a new R function and I think that's
what we'd have to do with messages.

So the "cost" of making the change is modifying the already complex eval
code without breaking anything and putting up with version mismash pains
for a period of time. My feeling is that catching messages from within
native code may not be worth these costs, at least right now (unless of
course the R_xlen_t change also has new header -> old lib breakage also in
which case this would actually be a good release to introduce the change).

**Comment by eddelbuettel** [comment]
All good points, and largely agree.  Not worth changing the world just to get `message()` to work, but while other changes are being we may as well slide it in (if and when it is fixed).

**Comment by kevinushey** [comment]
This should be resolved with the move away from `R_ToplevelExec`.
