### ISSUE TITLE
R CMD check and Rcpp.package.skeleton()

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#472]
Per [Creating R package with Rcpp: errors](http://stackoverflow.com/questions/37121897/creating-r-package-with-rcpp-errors?noredirect=1#comment61824110_37121897), it was noted that the CRAN check fails capriciously on the description file along with: documentation failure and dependency check issues.

Using `Rcpp.package.skeleton()` under the current CRAN build, Rcpp has the following CRAN check errors:

```
0 errors | 3 warnings | 2 notes
checking whether package ‘an2’ can be installed ... WARNING

checking Rd files ... WARNING
prepare_Rd: an2-package.Rd:26: All text must be in a section
prepare_Rd: an2-package.Rd:32-34: Dropping empty section \examples

checking Rd cross-references ... WARNING
Unknown package ‘<pkg>’ in Rd xrefs

checking DESCRIPTION meta-information ... NOTE
Malformed Description field: should contain one or more complete sentences.

checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘Rcpp’
  All declared Imports should be used.
```

Dirk already set up a patch for the description check [update-pkg-skeleton](https://github.com/RcppCore/Rcpp/tree/feature/update-pkg-skeleton) (see PR #471) leading to new Rcpp skeleton packages having:
```
checking Rd files ... WARNING
prepare_Rd: anRpackage-package.Rd:26: All text must be in a section
prepare_Rd: anRpackage-package.Rd:32-34: Dropping empty section \examples

checking Rd cross-references ... WARNING
Unknown package ‘<pkg>’ in Rd xrefs

checking dependencies in R code ... NOTE
Namespace in Imports field not imported from: ‘Rcpp’
  All declared Imports should be used.
```

I would highly suggest the addition of `importFrom(Rcpp,evalCpp)` to the `NAMESPACE` file so that users are only forced to modify one file the `*-package.Rd`.

**Comment by eddelbuettel** [comment]
As I mentioned in the [So comment of the thread where this started](http://stackoverflow.com/questions/37121897/creating-r-package-with-rcpp-errors?noredirect=1#comment61809584_37121897), the issue 

> checking Rd files ... WARNING
prepare_Rd: an2-package.Rd:26: All text must be in a section
prepare_Rd: an2-package.Rd:32-34: Dropping empty section \examples

has been taking care of for years by farming out to [pkgKitten](http://dirk.eddelbuettel.com/code/pkgkitten.html) which has a `Suggests:`.  So I consider this issue closed.   You can tru to convince me otherwise.

Now, before I committed and the PRed what is now in #471 I also tested the thusly-created package... and got it again to be squeaky-clean (provided you have [pkgKitten](http://dirk.eddelbuettel.com/code/pkgkitten.html)).

The whole issue is somewhat ridiculous as we have package creators in

- R itself (but sucky, hence  [pkgKitten](http://dirk.eddelbuettel.com/code/pkgkitten.html))
-  [pkgKitten](http://dirk.eddelbuettel.com/code/pkgkitten.html)
- RStudio
- devtools (I think)

and probably a few more places I do not know about.

**Comment by eddelbuettel** [comment]
Below is a full log using the Rcpp code in the current PR.  I am inclined to close this.  Thoughts?

```
edd@max:/tmp$ r -e'Rcpp::Rcpp.package.skeleton("coatlessDemo")'
Creating directories ...
Creating DESCRIPTION ...
Creating NAMESPACE ...
Creating Read-and-delete-me ...
Saving functions and data ...
Making help files ...
Done.
Further steps are described in './coatlessDemo/Read-and-delete-me'.

Adding Rcpp settings
 >> added Imports: Rcpp
 >> added LinkingTo: Rcpp
 >> added useDynLib directive to NAMESPACE
 >> added importFrom(Rcpp, evalCpp) directive to NAMESPACE
 >> added example src file using Rcpp attributes
 >> compiled Rcpp attributes
 >> added Rd file for rcpp_hello_world
edd@max:/tmp$ R CMD build coatlessDemo
* checking for file ‘coatlessDemo/DESCRIPTION’ ... OK
* preparing ‘coatlessDemo’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘coatlessDemo_1.0.tar.gz’

edd@max:/tmp$ RD --version
R Under development (unstable) (2016-05-07 r70591) -- "Unsuffered Consequences"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.

edd@max:/tmp$ RD CMD check --as-cran coatlessDemo_1.0.tar.gz 
* using log directory ‘/tmp/coatlessDemo.Rcheck’
* using R Under development (unstable) (2016-05-07 r70591)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using option ‘--as-cran’
* checking for file ‘coatlessDemo/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘coatlessDemo’ version ‘1.0’
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Your Name <your@email.com>’

New submission
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘coatlessDemo’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking examples ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 NOTE
See
  ‘/tmp/coatlessDemo.Rcheck/00check.log’
for details.


edd@max:/tmp$ 
```

**Comment by coatless** [comment]
Here it goes...

I do not think the install base has pkgKitten or even the understanding behind pkgKitten is known to the larger community. As the name of pkgKitten does not convey its intent outside of the internet's affinity for cats. So, while it might solve this issue entirely, as pointed out above, it does so for a small percentage of the community that could likely diagnosis and fix the issue themselves.

With this being said, it is particularly problematic as users who are creating skeleton packages have little experience or are being told this is the correct way to embed c++ code under the Rcpp scheme. Furthermore, the importFrom error and the lack of a usedynload statement within NAMESPACE has been shown to cause issues that frequently end up on SO. (On mobile, will add later). 

Thus, I would suggest changing the dependence with pkgKitten so it is automatically included or directly fixing the generation within the the skeleton version of Rcpp.

Apologies for the delay as I am now traveling

**Comment by eddelbuettel** [comment]
The download count does not matter all that much because many people just _run_ code with Rcpp--thing dplyr and all its friends.   And for those actually writing code with Rcpp, I am thinking that a Suggests: should do.  Just as it does for RUnit, say.  

One thing we could of course do is to add a note in the Rcpp FAQ.  pkgKitten is not yet mentioned in any vignettes.   

In any event, I hear you---I am as bugged as you are by packages created freshly by proper tools (like `package.skeleton()`) yet which fail to cleanly pass `R CMD check`.  But I want to treat lightly on additional Depends:.  It really is just for one function which we could even duplicate (as inelegant as that is).

Any thought from @jjallaire @kevinushey @thirdwing ?

**Comment by jjallaire** [comment]
I'd be in favor of duplicating it so that we are always guaranteed to
create a clean package.

On Tue, May 10, 2016 at 6:21 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
I think I agree. 

We can keep the 'Suggests: pkgKitten' as a free option in case functionality on that side gets added.  But otherwise, it really is just [these few lines](https://github.com/eddelbuettel/pkgkitten/blob/master/R/pkgKitten.R#L141-158) so we may as well import them. I'll get to that tomorrow.

**Comment by eddelbuettel** [comment]
@coatless I made one more change and this is now in the mainline.  Can you take a peek?   Should now create a _purring_ little package even when pkgKitten is not around to help.

**Comment by coatless** [comment]
@eddelbuettel 

d6350894c3b7dfa44477057d6c4387f2cac3adf3 's `Rcpp.package.skeleton()` generated package passes the CRAN check as tested on Windows 10 with R 3.3.0.

Thanks! 

(Misc Note: It may yield issues under `devtools::check()` since `roxygen2` is not used to generate the NAMESPACE. But, that is minor as `devtools::check(document = F)` fixes it.)

**Comment by eddelbuettel** [comment]
@coatless Thanks.  

Re your _misc note_: Whether or not you let `roxygen2` play with `DESCRIPTION` and/or `NAMESPACE` should be entirely orthogonal to this package.  The only relevant commands, really, are `R CMD ...` as in [WRE](https://cran.r-project.org/doc/manuals/r-release/R-exts.html).
