### ISSUE TITLE
g++ not found

### ISSUE THREAD

**Issue by ssamberkar** [RcppCore/Rcpp#491]
Dear All,

I'm trying to install Rcpp from cran (Rcpp_0.12.5.tar.gz), however I'm getting g++ command not found, despite having it. I must note I have to load it into the environment using the "module load" command as I'm trying this on a HPC. I get the following error:
`
make: g++-4.9.2: Command not found
make: *** [Date.o] Error 127
ERROR: compilation failed for package ‘Rcpp’
`
Can someone please help me with this? Many thanks.
Best,
SSA

**Comment by eddelbuettel** [comment]
Your problem -- your R setup is messed. Talk to your sysadmins / HPC helpers.

This **must** work for R to find a compiler so that Rcpp can be used:

```
edd@don:~$ R CMD config CXX
g++
edd@don:~$ 
```

It obviously also needs to remain in sync -- if you had, say, g++-4.8 and then upgrade to g++-4.9 _only_ you need to reset this.  R has plenty of documentation about it.

I will close this it has nothing to do with Rcpp -- we rely on on features missing in your local setup.
