### ISSUE TITLE
Constructor from a const NumericVector&

### ISSUE THREAD

**Issue by privefl** [RcppCore/Rcpp#627]
```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
NumericVector timesTwo(const NumericVector& x) {
  NumericVector xx(x);
  xx = xx * 2;
  return x;
}

/*** R
x <- 1:10
(new.x <- timesTwo(x))
*/
```
This returns the **double** of `x`.
So, two questions:
- `NumericVector xx(x)` isn't a constructor by copy? (Same question for `xx = xx * 2`)
- Should `const` protect `x` from being modified?

If this is normal behaviour (not a bug), could you provide a link to a detailed reference manual for Rcpp? 

Thanks

(I have R version 3.3.2 and Rcpp version 0.12.8)

**Comment by eddelbuettel** [comment]
See the various discussions of _proxy object_ in the Rcpp documentation.   

All the underlying `SEXP` we access are passed by reference without explicit copies.  Sometimes, however , C++ makes us do copies by casting.  Try the above with `x <- c(1L, 2L, 3L, 4L)` (or anything else that is `integer`).  It will be copied to `NumericVector` first.

The issue is at the same time subtle, important and yet fairly widely discussed.

**Comment by privefl** [comment]
Thanks for the quick answer.
I know that the type of the vector should be `double` to pass it without copy to Rcpp. 
My questions were more on why modifying `xx` inside the Rcpp function modifies `x` also.

**Comment by eddelbuettel** [comment]
Because it is a proxy and passed by reference ("pointer") by construction.  That is how we communicate with the C project that R and its API.  The `const` in your interface is just cosmetic: we cannot force C++ behaviour on this.

If you want a distinct copy, use `Rcpp::NumericVector xx = Rcpp:clone(x);`.

**Comment by privefl** [comment]
Okay I understand now why `x` is also modified.

When you say that the `const` is cosmetic, you mean useless?
It does prevents me from writing things like `x[0] = 0;`.

**Comment by eddelbuettel** [comment]
Sort of. I think in some cases the compiler catches it and warns you.

But it is nowhere as ironclad as a pure C++ approach would be.  It's just different -- we're playing the hand we've been dealt.

**Comment by eddelbuettel** [comment]
That said, this should an entry in the Rcpp FAQ and currently does not.  

Most of the prior discussions, it seems, were on the mailing list or SO.
