### ISSUE TITLE
Overhead in .length()

### ISSUE THREAD

**Issue by twolodzko** [RcppCore/Rcpp#629]
`.size()` for `std::vector` [works in constant time](http://stackoverflow.com/questions/3221969/is-repeatedly-calling-size-on-a-container-during-loop-bad), while `.length()` for vectors in Rcpp seems to be approximately 1.5 times slower according to benchmarks I've done.

**Comment by eddelbuettel** [comment]
Judging wrong the visual avatar, I suspect you are the same person who [just asked on SO](http://stackoverflow.com/questions/41602024/should-i-prefer-rcppnumericvector-over-stdvector) soaking up some time from myself and @coatless.

I can only deplore you to please PLEASE *PLEASE* not open an avalanche of questions here until you actually have at least a modicum of understanding of the internal representations of the R objects, and hence their Rcpp wrappers.

That `.length()` has different performance between gets you a quick _so what?_ from me.  If the cost is measured in what I presume to be nanoseconds I don't care too much about a small penalty.  Now, if you actually ended up bringing us a PR with an improved `.length()` _without creating side effects_ then I might listen.  Right now I am underimpressed.

**Comment by nathan-russell** [comment]
@twolodzko Just to follow up, you misunderstand the meaning of constant time complexity, which has nothing to do with the (absolute) amount of time it takes to perform an operation on a given input -- it is a (relative) measurement of time complexity *as a function of input size*. In this case, the constant time complexity guarantee provided by `std::vector::size` just means that calling `x.size()` takes the same amount of time regardless of the length of `x`. Since the `vector` class stores its length as a member variable, nothing is being *computed* when you call `size()`; it is simply returning a predetermined value. 

This is also the case for Rcpp vectors: [`Rcpp::Vector::size` just calls `Rf_xlength`](https://github.com/RcppCore/Rcpp/blob/master/inst/include/Rcpp/vector/Vector.h#L274-L276), which ultimately makes a call to the [`LENGTH` macro](https://github.com/wch/r-source/blob/4a9ca3e5ac6b19d7faa7c9290374f7604bf0ef64/src/include/Rinternals.h#L382) (or equivalent), an internal R function: 

```c++
# define LENGTH(x)	(((VECSEXP) (x))->vecsxp.length)
``` 

As you can see, this is simply accessing the [`length` member](https://github.com/wch/r-source/blob/4a9ca3e5ac6b19d7faa7c9290374f7604bf0ef64/src/include/Rinternals.h#L214) in the [underlying data structure](https://github.com/wch/r-source/blob/4a9ca3e5ac6b19d7faa7c9290374f7604bf0ef64/src/include/Rinternals.h#L293-L296), meaning that `Rf_xlength`, and by extension, `Rcpp::Vector::size`, **also has constant time complexity**. Any difference you are seeing between the performance of `std::vector::size` and `Rcpp::Vector::size` is almost certainly due to a flaw in the design of your benchmark.

**Comment by jjallaire** [comment]
Any difference in performance is likely just based on the cost of the
pointer indirection and/or inlining. There is nothing to do here.

**Comment by twolodzko** [comment]
@nathan-russell @eddelbuettel thanks for comments and sorry for bothering, it seems that I might have missed something in the code I was working on. Next time I'll try abstain from posting bug notices at nightly hours ;)

**Comment by eddelbuettel** [comment]
No worries. We've all been there...  For simple 'why X do foo' questions the mailing list is good too.
