### ISSUE TITLE
ChangeLog is stale

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#75]
ChangeLog is useful as a higher-level description as it is shipped with the source tar ball.  

It would be nice if some level of granularity could be maintained. Maybe an entry every five or ten commits?

**Comment by coatless** [comment]
This issue is definitely resolved as is evident by the [ChangeLog](https://github.com/RcppCore/Rcpp/commits/master/ChangeLog) and [NEWS.Rd](https://github.com/RcppCore/Rcpp/blob/master/inst/NEWS.Rd) entries. 

Procedure of updating ChangeLog & NEWS.Rd has also been added to [Contributing.md](https://github.com/RcppCore/Rcpp/blob/master/Contributing.md) per PR #414 and Issue #413 


Please close. (Tagging #506 )
