### ISSUE TITLE
NEWS.Rd is stale

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/Rcpp#76]
NEWS is *the* high-level summary of changes. It is also prominently shown on the CRAN page.

It would be nice if some higher granularity could be maintained. Maybe an entry every ten, twenty, thirty commits to summarize big level topic changes ?

**Comment by coatless** [comment]
This issue is definitely resolved as is evident by the [ChangeLog](https://github.com/RcppCore/Rcpp/commits/master/ChangeLog) and [NEWS.Rd](https://github.com/RcppCore/Rcpp/blob/master/inst/NEWS.Rd) entries. 

Procedure of updating ChangeLog & NEWS.Rd has also been added to [Contributing.md](https://github.com/RcppCore/Rcpp/blob/master/Contributing.md) per PR #414 and Issue #413 


Please close. (Tagging #506 )
