### ISSUE TITLE
"Function" with quoted R expression as argument

### ISSUE THREAD

**Issue by Marlin-Na** [RcppCore/Rcpp#983]
For the following example, I would expect that `call_r_function_from_cpp` and `r_callback` return same results. However, in the case that argument is an expression, "Function" apparently tries to interpret it differently and leads to an error. 

I am not sure if this is an intentional behavior (e.g. for an alternative way to construct the function call?). But I think it would be helpful to have an alternative way to call the function that does not interpret EXPRSXP/LANGSXP/SYMSXP differently than other R objects. Maybe something like `Function::call(f, arg1, arg2)`?

```cpp
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
SEXP call_r_function_from_cpp(SEXP x) {
    Function r_function = Environment::global_env()["r_callback"];
    return r_function(x);
}


/*** R
r_callback <- function(x) {
    typeof(x)
}

call_r_function_from_cpp(42)
r_callback(42)

call_r_function_from_cpp(quote(x))
r_callback(quote(x))
*/
```

```r
call_r_function_from_cpp(quote(x))
# Error in call_r_function_from_cpp(quote(x)) : 
#   Evaluation error: object 'x' not found.
r_callback(quote(x))
# [1] "symbol"
```

**Comment by eddelbuettel** [comment]
First of, your example misses an `x`.  Second, I am not sure I care all that much.  Once I add _e.g._ `x <- 27` I get 

```
R> x <- 27

R> call_r_function_from_cpp(quote(x))
[1] "double"

R> r_callback(quote(x))
[1] "symbol"
R> 
```

If you want to mix non-standard evaluation and dispatch to C++ you may need to add some more layers.

**Comment by eddelbuettel** [comment]
@lionel-  Do you want to chime in here?  Are there any low-hanging fruits for us?

**Comment by lionel-** [comment]
The standard way to deal with this is to wrap all symbolic arguments (`SYMSXP` and `LANGSXP`) in calls to `quote()`. You can embed the quote primitive in the call to avoid masking issues (see patch in https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17488), or you could at least make it `base::quote()`.

This will have an effect on captured calls and backtraces.

**Comment by Marlin-Na** [comment]
Thanks @lionel- , it works for my use case. I am using the following helper function to "protect" `SYMSXP` and `LANGSXP`:

```cpp
static SEXP quote_cpp(SEXP x) {
    if (!(TYPEOF(x) == SYMSXP || TYPEOF(x) == LANGSXP))
        return x;
    SEXP prim = PROTECT(Rf_install(".Primitive"));
    SEXP quot = PROTECT(Rf_mkString("quote"));
    SEXP head = PROTECT(Rf_lang2(prim, quot));
    SEXP ans = PROTECT(Rf_lang2(head, x));
    UNPROTECT(4);
    return ans;
}

// [[Rcpp::export]]
SEXP call_r_function_from_cpp(SEXP x) {
    Function r_function = Environment::global_env()["r_callback"];
    return r_function(quote_cpp(x));
}
```


```r
r_callback <- function(x) {
   print(sys.call())
   print(typeof(x))
   x
}
expr <- quote(m + z)
call_r_function_from_cpp(expr)
# (function(x) {
#     print(sys.call())
#     print(typeof(x))
#     x
# })(.Primitive("quote")(m + z))
# [1] "language"
# m + z
```

**Comment by eddelbuettel** [comment]
And I think you can do one better than `quote_cpp` by using `Rcpp::Function` and `Rcpp::Shield`.  A short worked example like this may be useful for the Rcpp Gallery...

**Comment by Marlin-Na** [comment]
:relieved: Unfortunately I am not familiar with `Rcpp::Shield`. But maybe something like:

```cpp
static RObject quote_cpp(RObject x) {
    if (x.sexp_type() != SYMSXP && x.sexp_type() != LANGSXP)
        return x;
    RObject prim = Rf_install(".Primitive");
    RObject quot = Rf_mkString("quote");
    RObject head = Rf_lang2(prim, quot);
    return Rf_lang2(head, x);
}
```
I am not sure how to make this more concise... Also note that we can not use `Environment::base_env()["quote"]`, i.e. `Rcpp::Function`. The `base::quote` should be embed with the call.

**Comment by lionel-** [comment]
```
    SEXP prim = PROTECT(Rf_install(".Primitive"));
    SEXP quot = PROTECT(Rf_mkString("quote"));
```

This could be simplified a bit by plucking `quote` from `R_BaseEnvironment`. This way you directly have the `SPECIALSXP` in the CAR of your call, instead of a `LANGSXP`. This is a bit confusing because both deparse the same way in the console:

```r
c1 <- as.call(list(quote, 1))
c2 <- as.call(list(quote(.Primitive("quote")), 1))

c1
#> .Primitive("quote")(1)

c2
#> .Primitive("quote")(1)
```

Inlining the primitive creates a simpler call and is a tiny bit safer (doesn't rely on correct `.Primitive` binding being in scope):

```r
typeof(c1[[1]])
#> [1] "special"

typeof(c2[[1]])
#> [1] "language"
```

**Comment by Marlin-Na** [comment]
@lionel- Thanks - that's very interesting. Didn't know about `SPECIALSXP` before.

**Comment by kevinushey** [comment]
I believe the underlying issue here is that we evaluate the function arguments eagerly, which is different from how things are done with regular R evaluation. For example, with:

```
call_r_function_from_cpp(quote(x))
```

We evaluate the argument `quote(x)`, end up with the symbol `x`, and insert that into the argument list for the function to be called:

```
(function(x) { typeof(x) })(x)
```

A similar way to demonstrate this:

```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
SEXP call_r_function_from_cpp(SEXP x) {
  Function r_function = Environment::global_env()["r_callback"];
  return r_function(x);
}


/*** R
r_callback <- function(x) {
  writeLines("> in r_callback")
  force(x)
}

r_callback(x = writeLines("> evaluating x"))
call_r_function_from_cpp(x = writeLines("> evaluating x"))
*/
```

If you source that, you should see:

```
> r_callback(x = writeLines("> evaluating x"))
> in r_callback
> evaluating x

> call_r_function_from_cpp(x = writeLines("> evaluating x"))
> evaluating x
> in r_callback
```

I believe handling this properly would mean forwarding along the promises originally generated by R.

**Comment by coatless** [comment]
I don't think _R_ core would approve of that modification based on recent comments by Luke:

> Just to clarify: promises are an internal mechanism for implementing lazy evaluation. Keeping them internal allows us to optimize performance e.g. by not allocating promises when not needed. This would not be possible if packages depended on the specific current implementation.
>
> ---- [Luke Tierney](https://twitter.com/LukeTierney4/status/1155214332256346112) Jul 27, 2019

**Comment by kevinushey** [comment]
I'm not proposing anything using internal APIs -- rather, we need to avoid evaluating the promise given to us by R and instead just pass it along to the call we generate.

**Comment by Marlin-Na** [comment]
Hi @kevinushey , I think this issue is unrelated to promise. Note that even I use
```
expr <- quote(x)
r_callback(expr)
call_r_function_from_cpp(expr)
```
It has the same issue.

**Comment by lionel-** [comment]
Another way is to pass the parameter symbol of the Rcpp wrapper, along with its local environment:

```r
wrapper <- function(arg) {
  # `arg` is a promise to the caller's argument
  .Call(rcpp, quote(arg), environment())
}
```

Then a call with `arg` is constructed and evaluated in the environment. Compared to quote-protection, this creates better captured calls in backtraces etc. 

Equivalently the wrapper could take the arguments by value and bind them in a new environment (and possibly also bind the function). We also use that idiom in r-lib, e.g. https://github.com/r-lib/vctrs/blob/0fe81688c3b4c32ec3ff927c3c78b2f842cf067f/src/utils.c#L52.

Kevin's idea could be implemented by binding the original promises to the symbols, instead of binding values. Then `substitute()` should work correctly, if that matters here. However `match.call()`, `traceback()` etc do not use promises to capture the calls and so will not include the original argument expressions. Regarding the internal API, you can get the PROMSXP object with `Rf_findVar()`, but I don't think this behaviour is officially documented.

**Comment by kevinushey** [comment]
I like the idea of using a wrapper that passes quoted arguments and the associated environment. It seems like we could make this change transparently to the user (we'd just need to alter the generated code in RcppExports.R and RcppExports.cpp).
