### ISSUE TITLE
C++ function returns variable to global R-workspace

### ISSUE THREAD

**Issue by PhilippBuehler** [RcppCore/Rcpp#984]
I pass a list to a c++-function and iterate over that list. The list, which i use as input in R changes every time I call the c++ function, even if I supress output by void. Also the variable names inside my c++ function arent the same as in my R Script.

```
inds <- lapply(1:1, function(x) x)

cppFunction('void teste(const List test_var) {
  const int size_l = test_var.size(); 
  int l;
  IntegerVector cur_inds;

  
  for (l = 0; l < size_l ; l++) {
    cur_inds = test_var[l];
    cur_inds = cur_inds -1;
    }
 }')


for(i in 1:10){
  teste(inds)
  print(inds[[1]])
} 
```

**Comment by eddelbuettel** [comment]
Yes, because the (only) interface from R is `SEXP .Call(yourfunctionname, SEXP, SEXP, SEXP, ...)` and the S Expression Pointers are in fact pointers.   

If you want your function to not mutate the input argument, you need to ensure you do not alter your input arguments, for example by making (deep) copies using `Rcpp::copy(var)`.

**Comment by PhilippBuehler** [comment]
Thank you for the detailed explanation of the behaviour. Is the pointer reference and therefore the modification of it only for list-like objects?

**Comment by eddelbuettel** [comment]
As I said, `SEXP .Call(SEXP, SEXP, SEXP, ...)` is the only interface.  Meaning it is used for everything, not only lists.

**Comment by stephematician** [comment]
A `List` is essentially a container for references to the items contained in that list. By declaring the `List` as `const` that means that you cannot add or remove or otherwise change _which_ items are in the list - but you can change the contents of an item (using exactly the pattern in your example). This isn't true of many other Rcpp templates.

**Comment by eddelbuettel** [comment]
Closing, this is a usage question better suited to StackOverflow.
